[package]
name = "hook-inject-build"
version = "0.1.0"
edition = "2024"

[features]
default = ["auto-detect"]
auto-detect = []
download-devkit = []
build-utils = ["dep:pkg-config"]

[dependencies]
toml = "0.9"
pkg-config = { version = "0.3", optional = true }
